import React from 'react';
import { SuggestedCoordinate } from '../types';

interface ResultDisplayProps {
  suggestion: SuggestedCoordinate;
  imageUrl: string | null;
  isImageLoading: boolean;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ suggestion, imageUrl, isImageLoading }) => {
  return (
    <div className="space-y-6 animate-fade-in-up">
      {/* Title & Description */}
      <div className="bg-white p-6 rounded-xl shadow-lg border-l-8 border-indigo-600">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">{suggestion.title}</h2>
        <p className="text-gray-700 leading-relaxed">{suggestion.description}</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Logic / Theory Section */}
        <div className="space-y-6">
          <div className="bg-white p-6 rounded-xl shadow-md">
            <h3 className="text-lg font-bold text-indigo-900 mb-3 border-b pb-2 flex items-center">
              <span className="mr-2">📐</span> シルエット理論
            </h3>
            <p className="text-gray-700 text-sm leading-relaxed">{suggestion.silhouetteTheory}</p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-md">
            <h3 className="text-lg font-bold text-indigo-900 mb-3 border-b pb-2 flex items-center">
              <span className="mr-2">🎨</span> 配色理論
            </h3>
            <p className="text-gray-700 text-sm leading-relaxed">{suggestion.colorTheory}</p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-md">
            <h3 className="text-lg font-bold text-indigo-900 mb-3 border-b pb-2 flex items-center">
              <span className="mr-2">👕</span> 推奨アイテム
            </h3>
            <ul className="list-disc pl-5 space-y-1">
              {suggestion.items.map((item, idx) => (
                <li key={idx} className="text-gray-700">{item}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Image Section */}
        <div className="bg-white p-4 rounded-xl shadow-md flex flex-col items-center justify-center min-h-[300px]">
          <h3 className="text-lg font-bold text-gray-800 mb-4 w-full text-left">着用イメージ (AI生成)</h3>
          
          {isImageLoading ? (
            <div className="flex flex-col items-center justify-center space-y-4 text-gray-500 py-12">
              <div className="w-12 h-12 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin"></div>
              <p className="animate-pulse font-medium">画像生成中... (nano banana)</p>
            </div>
          ) : imageUrl ? (
            <div className="relative w-full rounded-lg overflow-hidden shadow-inner group">
              <img 
                src={imageUrl} 
                alt="Generated Coordinate" 
                className="w-full h-auto object-cover transform transition duration-500 group-hover:scale-105"
              />
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                <p className="text-white text-xs">Generated by Gemini 2.5 Flash Image</p>
              </div>
            </div>
          ) : (
             <div className="text-gray-400 text-center py-10">
               画像を生成できませんでした。
             </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ResultDisplay;
